### ISSUE TITLE
Error when opening maps browser on Kodi 17 and 17.1

### ISSUE THREAD

**Issue by AnthonyBe** [phil65/script.maps.browser#5]
http://forum.kodi.tv/showthread.php?tid=311851

`14:40:34.665 T:1350231024   ERROR: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                             - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                            Error Type: <type 'exceptions.AttributeError'>
                                            Error Contents: 'module' object has no attribute 'ACTION_SHOW_CODEC'
                                            Traceback (most recent call last):
                                              File "/home/osmc/.kodi/addons/script.maps.browser/default.py", line 23, in <module>
                                                from resources.lib import gui
                                              File "/home/osmc/.kodi/addons/script.maps.browser/resources/lib/gui.py", line 17, in <module>
                                                from ActionHandler import ActionHandler
                                              File "/home/osmc/.kodi/addons/script.module.actionhandler/lib/ActionHandler.py", line 37, in <module>
                                                "codecinfo": xbmcgui.ACTION_SHOW_CODEC,
                                            AttributeError: 'module' object has no attribute 'ACTION_SHOW_CODEC'
                                            -->End of Python script error report<--
14:40:34.691 T:1958536112   DEBUG: ------ Window Init (DialogNotification.xml) ------`

**Comment by MarcSaric** [comment]
Similar error here with Ubuntu 14.04.5 LTS (GNU/Linux 3.13.0-128-generic i686) running latest KODI 17.3 Git:20170525-nogitfound.

**Comment by arabesc** [comment]
Same issue here - Windows 10 / Kodi v17.6 / Maps Browser v1.0.0
```
21:09:19.728 T:14152   ERROR: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                             - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                            Error Type: <type 'exceptions.AttributeError'>
                                            Error Contents: 'module' object has no attribute 'ACTION_SHOW_CODEC'
                                            Traceback (most recent call last):
                                              File "C:\Users\kodi\AppData\Roaming\Kodi\addons\script.maps.browser\default.py", line 23, in <module>
                                                from resources.lib import gui
                                              File "C:\Users\kodi\AppData\Roaming\Kodi\addons\script.maps.browser\resources\lib\gui.py", line 17, in <module>
                                                from ActionHandler import ActionHandler
                                              File "C:\Users\kodi\AppData\Roaming\Kodi\addons\script.module.actionhandler\lib\ActionHandler.py", line 37, in <module>
                                                "codecinfo": xbmcgui.ACTION_SHOW_CODEC,
                                            AttributeError: 'module' object has no attribute 'ACTION_SHOW_CODEC'
                                            -->End of Python script error report<--
```

**Comment by Steven1408** [comment]
Same Issue Raspberry Pi 3 with OSMC Kodi (January, 2018) 



```
18:56:35.690 T:1602220800 WARNING: COMXImageFile::GetCodingType progressive images not supported by decoder
18:56:35.690 T:1602220800  NOTICE: LoadJpeg: unable to load special://skin/backgrounds/music.jpg
18:56:47.721 T:1309049600   ERROR: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                             - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                            Error Type: <type 'exceptions.AttributeError'>
                                            Error Contents: 'module' object has no attribute 'ACTION_SHOW_CODEC'
                                            Traceback (most recent call last):
                                              File "/home/osmc/.kodi/addons/script.maps.browser/default.py", line 23, in <module>
                                                from resources.lib import gui
                                              File "/home/osmc/.kodi/addons/script.maps.browser/resources/lib/gui.py", line 17, in <module>
                                                from ActionHandler import ActionHandler
                                              File "/home/osmc/.kodi/addons/script.module.actionhandler/lib/ActionHandler.py", line 37, in <module>
                                                "codecinfo": xbmcgui.ACTION_SHOW_CODEC,
                                            AttributeError: 'module' object has no attribute 'ACTION_SHOW_CODEC'
                                            -->End of Python script error report<--
18:57:14.706 T:1602220800   ERROR: DoWork - Direct texture file loading failed for resource://resource.images.weathericons.default/
```

**Comment by helviojr** [comment]
I used version 1.1.0 and that error disappeared in Leia 18.0. It is not, although, published in Kodi repository, so you would need to go to 'master' branch root (here in GitHub) and download the zip, then, install from zip (not sure if necessary, but I uninstalled version 1.0.0 before.

**Comment by Steven1408** [comment]
I installed the Addon from the *.zip and it worked flawless. I am still on a Raspberry Pi with OSMC from January 2018. YES TOOK ME A YEAR (almost).

**Comment by Themanwithoutaplan** [comment]
Just an update on this: even with the master branch is likely to fail for other reasons (I'm on Libreelec): `from builtins import str` in resources/lib/gui.py requires the "future" library to be installed. But even then, the code is so old that it depends on kodi65. 

This is probably all fixable with little effort and I might give it a go, if I can work out how to setup a local kodi development environment.
